[project]
name = "amrita-place"
version = "1.0.0"
dependencies = [
"flask",
"pymysql",
"flask-sqlalchemy",
"cryptography",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
